### ISSUE TITLE
Sorting issue in search results for API response

### ISSUE THREAD

**Issue by chintankotadia** [ishgroup/lightbook#36]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lightbook/ldap_api/ldap_auth.py", line 19, in decorated
    return f(*args, **kwargs)
  File "/var/lightbook/production.py", line 141, in search_entry
    'peoples': ldap().search(search, 'people', get_disabled),
  File "/var/lightbook/ldap_api/ldap_service.py", line 139, in search
    return self.map_ldap_response(ldap_response, base).sort()
TypeError: '<' not supported between instances of 'dict' and 'dic
```

**Comment by chintankotadia** [comment]
In Python 3, dictionaries are no longer sortable together. We will need to use value as the sorting key. For e.g.

`response.sort(key=lambda k: k['name'].lower(), reverse=False)`
